version = 5.0.0
archive_dir = /etc/letsencrypt/archive/algoboost.foo
cert = /etc/letsencrypt/live/algoboost.foo/cert.pem
privkey = /etc/letsencrypt/live/algoboost.foo/privkey.pem
chain = /etc/letsencrypt/live/algoboost.foo/chain.pem
fullchain = /etc/letsencrypt/live/algoboost.foo/fullchain.pem
[renewalparams]
account = dccc7a863e9a88bf0414d2b15b34eb78
authenticator = webroot
webroot_path = /usr/share/nginx/html,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
algoboost.foo = /usr/share/nginx/html
www.algoboost.foo = /usr/share/nginx/html
[acme_renewal_info]
ari_retry_after = 2025-09-08T01:47:53
